# Generated by Django 2.2 on 2024-03-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_question_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
    ]
